input {
  tcp {
    port => 5044
    codec => json_lines
  }
  udp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [level] {
    mutate {
      rename => { "level" => "log_level" }
    }
  }
  date {
    match => ["@timestamp", "ISO8601"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "warehouse-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
