events {
    worker_connections 1024;
}

http {
    upstream users-service      { server users-service:8080; }
    upstream addtovar-service   { server addtovar-service:8080; }
    upstream vtovar-service     { server vtovar-service:8080; }
    upstream return-service     { server return-service:8080; }
    upstream rashodniki-service { server rashodniki-service:8080; }

    server {
        listen 80;

        # Фронтенд
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # API маршруты
        location /api/auth/       { proxy_pass http://users-service/api/auth/;            proxy_set_header Host $host; }
        location /api/product/    { proxy_pass http://addtovar-service/api/product/;      proxy_set_header Host $host; }
        location /api/issuance/   { proxy_pass http://vtovar-service/api/issuance/;       proxy_set_header Host $host; }
        location /api/return/     { proxy_pass http://return-service/api/return/;         proxy_set_header Host $host; }
        location /api/rashodniki/ { proxy_pass http://rashodniki-service/api/rashodniki/; proxy_set_header Host $host; }
    }
}
